<template>
  <div>
    <v-toolbar
      app
      dark
      clipped-left
      color="primary"
    >
      <v-toolbar-title
        class="headline"
      >
        ApiHub
      </v-toolbar-title>
      <v-spacer />
      <v-btn
        icon
      >
        <v-icon>home</v-icon>
      </v-btn>
      <v-btn
        icon
      >
        <v-icon>apps</v-icon>
      </v-btn>
    </v-toolbar>
  </div>
</template>
